### ISSUE TITLE
Unable to run on a Xserver less machine

### ISSUE THREAD

**Issue by vfbsilva** [ashutoshraj/SignatureRecognition#3]
Hello I seem to hit an error from _tkinter.TclError: no display name and no $DISPLAY environment variable despite the fact I'm running with the --visual=False. What can I be missing?

**Comment by ashutoshraj** [comment]
You need to comment, wherever the GUI applications are running, such as plt.imshow or cv2.imshow commands in the code.

**Comment by vfbsilva** [comment]
@ashutoshraj also did that on
```
plt.imshow(img3)
        plt.show()
```
